DROP DATABASE IF EXISTS total_war_info;

CREATE DATABASE total_war_info;
\c total_war_info;

CREATE TABLE public."Hero" (
	"DAMAGE0" NUMERIC NOT NULL, 
	"DAMAGEA" NUMERIC NOT NULL, 
	"DAMAGEDELAY" NUMERIC NOT NULL, 
	"MAXHP0" NUMERIC NOT NULL, 
	"MAXHPA" NUMERIC NOT NULL, 
	"MAXSTEP" NUMERIC NOT NULL,
	"SPEC0" NUMERIC NOT NULL, 
	"SPECA" NUMERIC NOT NULL, 
	"SPECB" NUMERIC NULL, 
	"SPECDELAY" NUMERIC NOT NULL, 
	"SPEED0" NUMERIC NOT NULL, 
	"SPEEDA" NUMERIC NOT NULL,
	"actualSpeed" NUMERIC NOT NULL, 
	"animationAttack" TEXT NOT NULL, 
	"animationBlinking" TEXT NOT NULL, 
	"animationDamage" TEXT NOT NULL, 
	"animationDying" TEXT NOT NULL,
	"animationIdle" TEXT NOT NULL, 
	"animationSpec" TEXT NOT NULL, 
	"animationTaunt" TEXT NOT NULL, 
	"animationWalking" TEXT NOT NULL, 
	"attackType" TEXT NOT NULL, 
	"attackDamage" NUMERIC NOT NULL, 
	"attackDelay" NUMERIC NOT NULL,
	"maxHp" NUMERIC NOT NULL, 
	"maxLevel" NUMERIC NOT NULL, 
	"rarity" NUMERIC NOT NULL, 
	"specDelay" NUMERIC NOT NULL, 
	"specType" TEXT NOT NULL, 
	"specValue" NUMERIC NULL,
	"specialty" TEXT NOT NULL, 
	"speed" NUMERIC NOT NULL, 
	"type" TEXT NOT NULL
);

CREATE VIEW "PlayableHero" AS SELECT "type" AS Name, "rarity", "specialty", "maxHp" AS HP, "DAMAGE0" AS MeleeDamage, "SPEC0" AS SpecDamage, 
	"SPECDELAY" AS SpecDelay, "specType", "DAMAGEDELAY" AS MeleeDelay, "SPEED0" AS Speed 
	FROM "Hero" WHERE "maxLevel" <= 5;


/* 
const allUnits = document.getElementById('html-game-frame').contentWindow.allGameData.UnitFactory.getHeroTypes();

for(var i=0; i<allUnits.length; i++) { 
    let unit = document.getElementById('html-game-frame').contentWindow.allGameData.Player.instance.getUnit(allUnits[i]);
	if (unit.maxLevel <= 5) {
	  const SQL = `INSERT INTO public."Hero"(`
	     + `"DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", `
		 + `"actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", `
		 + `"animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", `
		 + `"specType", "specValue", "specialty", "speed", "type"`
		 + `) `
		 + `VALUES(${unit.DAMAGE0}, ${unit.DAMAGEA}, ${unit.DAMAGEDELAY}, ${unit.MAXHP0}, ${unit.MAXHPA}, ${unit.MAXSTEP}, ${unit.SPEC0}, ${unit.SPECA}, ${isNaN(unit.SPECB) ? null : unit.SPECB}, ${unit.SPECDELAY}, ${unit.SPEED0}, ${unit.SPEEDA}, `
		 + `${unit.actualSpeed}, '${unit.animationAttack}', '${unit.animationBlinking}', '${unit.animationDamage}', '${unit.animationDying}', '${unit.animationIdle}', '${unit.animationSpec}', '${unit.animationTaunt}', `
		 + `'${unit.animationWalking}', '${unit.attack.type}', ${unit.attack.value}, ${unit.attack.delay}, ${unit.maxHP.value}, ${unit.maxLevel}, ${unit.rarity}, ${unit.spec.delay}, `
		 + `'${unit.spec.type}', ${unit.spec.value}, '${unit.specialty}', ${unit.speed.value}, '${unit.type}'`
		 + `);`;
	  console.log(SQL);
	}
}
*/

INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(12, 0.1, 2.6, 200, 0.1, 10, 12, 0.1, 0.82, 5, 2.3, 4.6, -1, 'Attacking', 'Idle Blink', 'Hurt', 'Dying', 'Idle', 'Attacking', 'Taunt', 'Walking', 'Kick', 12, 2.6, 200, 5, 1, 5, 'Breaking', 12, 'Warrior', 2.3, 'IronHeart');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(18, 0.1, 2, 90, 0.1, 10, 14.5, 0.1, null, 4.2, 4, 8, -1, 'Attacking', 'Idle Blinking', 'Hurt', 'Dying', 'Idle', 'Attacking', 'Taunt', 'Walking', 'Kick', 18, 2, 90, 5, 1, 4.2, 'DoubleHit', 14.5, 'Warrior', 4, 'Assassin');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(10, 0.1, 2, 90, 0.1, 10, 30, 1.5, 500, 3.5, 3, 6, -1, 'Taunt', 'Idle Blinking', 'Hurt', 'Dying', 'Idle', 'Shooting', 'Taunt', 'Walking', 'Kick', 10, 2, 90, 5, 1, 3.5, 'FrostArrow', 30, 'Shooter', 3, 'Frost');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(22, 0.1, 2, 80, 0.1, 10, 46, 0.1, null, 4, 3, 6, -1, 'Attacking', 'Idle Blink', 'Hurt', 'Dying', 'Idle', 'Taunt', 'Taunt', 'Walking', 'Kick', 22, 2, 80, 5, 1, 4, 'Heal', 46, 'Mage', 3, 'WitcherGreen');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(6, 0.1, 2, 80, 0.1, 10, 25, 8, 2, 4, 2.3, 4.6, -1, 'Casting Spells', 'Idle Blinking', 'Hurt', 'Dying', 'Idle', 'Taunt', 'Taunt', 'Walking', 'Kick', 6, 2, 80, 5, 1, 4, 'Raise', 25, 'Mage', 2.3, 'Priest');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(10, 0.1, 2, 90, 0.1, 10, 32, 0.1, 532, 2.8, 3, 6, -1, 'Taunt', 'Idle Blinking', 'Hurt', 'Dying', 'Idle', 'Shooting', 'Taunt', 'Walking', 'Kick', 10, 2, 90, 5, 1, 2.8, 'Shoot', 32, 'Shooter', 3, 'Elf');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(12, 0.1, 2, 95, 0.1, 10, 40, 0.1, 540, 3.7, 3, 6, -1, 'Taunt', 'Idle Blinking', 'Hurt', 'Dying', 'Idle', 'Shooting', 'Taunt', 'Walking', 'Kick', 12, 2, 95, 5, 1, 3.7, 'Shoot', 40, 'Shooter', 3, 'Archer');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(16, 0.1, 2.5, 180, 0.1, 10, 20, 0.1, 0.6, 4.5, 2.3, 4.6, -1, 'Attacking', 'Idle Blink', 'Hurt', 'Dying', 'Idle', 'Attacking', 'Taunt', 'Walking', 'Kick', 16, 2.5, 180, 5, 1, 4.5, 'Stun', 20, 'Warrior', 2.3, 'Knight');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(18, 0.1, 2, 80, 0.1, 10, 50, 0.09, 2, 4, 2.3, 4.6, -1, 'Casting Spells', 'Idle Blinking', 'Hurt', 'Dying', 'Idle', 'Taunt', 'Taunt', 'Walking', 'Kick', 18, 2, 80, 5, 1, 4, 'Aura', 50, 'Mage', 2.3, 'Druid');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(8, 0.1, 2, 80, 0.1, 10, 36, 0.1, 510, 3.1, 3, 6, -1, 'Attacking', 'Idle Blink', 'Hurt', 'Dying', 'Idle', 'Taunt', 'Taunt', 'Walking', 'Kick', 8, 2, 80, 5, 2, 3.1, 'Fireball', 36, 'Mage', 3, 'WitcherRed');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(12, 0.1, 2, 120, 0.1, 10, 12, 0.1, 1.9, 4.5, 3, 6, -1, 'Attacking', 'Idle Blinking', 'Hurt', 'Dying', 'Idle', 'Attacking', 'Taunt', 'Walking', 'Kick', 12, 2, 120, 5, 2, 4.5, 'Freeze', 12, 'Warrior', 3, 'Subzero');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(20, 0.096, 2, 100, 0.1, 10, 32, 0.096, 100, 4, 3, 6, -1, 'Attacking', 'Idle Blinking', 'Hurt', 'Dying', 'Idle', 'Shooting', 'Taunt', 'Walking', 'Kick', 20, 2, 100, 5, 2, 4, 'HailOfArrows', 32, 'Shooter', 3, 'Hunter');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(24, 0.1, 2, 75, 0.1, 10, 48, 0.1, null, 4, 3, 6, -1, 'Casting Spells', 'Idle Blinking', 'Hurt', 'Dying', 'Idle', 'Healing', 'Taunt', 'Moving Forward', 'Kick', 24.72, 2, 88.5, 5, 2, 4, 'Heal', 48, 'Mage', 3, 'Fairy');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(22, 0.0983, 2, 120, 0.1, 10, 1.1, 2, null, 6, 3, 6, -1, 'Attacking', 'Idle Blinking', 'Hurt', 'Dying', 'Idle', 'Taunt', 'Taunt', 'Walking', 'Kick', 22, 2, 120, 5, 2, 6, 'Invisibility', 1.1, 'Warrior', 3, 'Dwarf');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(24, 0.0983, 2, 120, 0.1, 10, 1.1, 1, null, 4, 4, 8, -1, 'Attacking', 'Idle Blinking', 'Hurt', 'Dying', 'Idle', 'Attacking', 'Taunt', 'Walking', 'Kick', 24, 2, 120, 5, 2, 4, 'Revealing', 1.1, 'Warrior', 4, 'Stalker');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(14, 0.1, 2.2, 140, 0.1, 10, 15, 0.1, 0.8, 3.9, 3, 6, -1, 'Attacking', 'Idle Blink', 'Hurt', 'Dying', 'Idle', 'Attacking', 'Taunt', 'Walking', 'Kick', 14, 2.2, 140, 5, 2, 3.9, 'Stun', 15, 'Warrior', 3, 'Viking');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(24, 0.1, 2, 75, 0.1, 10, 10, 0.1, null, 4.5, 3, 6, -1, 'Casting Spells', 'Idle Blinking', 'Hurt', 'Dying', 'Idle', 'Healing', 'Taunt', 'Moving Forward', 'Kick', 24, 2, 75, 5, 2, 4.5, 'Swap', 10, 'Mage', 3, 'Princess');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(10, 0.1, 2, 90, 0.1, 10, 20, 0.1, 1000, 4, 3, 6, -1, 'Attacking', 'Idle Blinking', 'Hurt', 'Dying', 'Idle', 'Shooting', 'Taunt', 'Walking', 'Kick', 10, 2, 90, 5, 2, 4, 'WildArrow', 20, 'Shooter', 3, 'GreenArrow');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(24, 0.096, 2, 120, 0.1, 10, 1.05, 1, null, 5.4, 3, 6, -1, 'Attacking', 'Idle Blink', 'Hurt', 'Dying', 'Idle', 'Taunt', 'Taunt', 'Walking', 'Kick', 24, 2, 120, 5, 3, 5.4, 'BattleCry', 1.05, 'Warrior', 3, 'Konung');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(6, 0.0937, 2, 75, 0.0937, 10, 2, 4, null, 4.57, 3, 6, -1, 'Casting Spells', 'Idle Blinking', 'Hurt', 'Dying', 'Idle', 'Healing', 'Taunt', 'Moving Forward', 'Kick', 6, 2, 75, 5, 3, 4.57, 'Hypno', null, 'Mage', 3, 'Charmer');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(8, 0.1, 2, 80, 0.1, 10, 36, 0.1, 510, 3.1, 3, 6, -1, 'Attacking', 'Idle Blink', 'Hurt', 'Dying', 'Idle', 'Taunt', 'Taunt', 'Walking', 'Kick', 8, 2, 80, 5, 3, 3.1, 'Light', 36, 'Mage', 3, 'WitcherBlue');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(24, 0.099, 2, 141, 0.1, 10, 1.1, 1.3, null, 4, 3, 6, -1, 'Attacking', 'Idle Blink', 'Hurt', 'Dying', 'Idle', 'Taunt', 'Taunt', 'Walking', 'Kick', 24, 2, 141, 5, 3, 4, 'Motivation', 1.1, 'Warrior', 3, 'Commander');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(24, 0.0962, 2, 116, 0.1, 10, 1.1, 1.52, null, 4, 3, 6, -1, 'Attacking', 'Idle Blink', 'Hurt', 'Dying', 'Idle', 'Taunt', 'Taunt', 'Walking', 'Kick', 24, 2, 116, 5, 3, 4, 'MotivationAll', 1.1, 'Warrior', 3, 'King');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(24, 0.099, 2, 141, 0.1, 10, 1.1, 1.3, null, 4, 3, 6, -1, 'Attacking', 'Idle Blink', 'Hurt', 'Dying', 'Idle', 'Taunt', 'Taunt', 'Walking', 'Kick', 24, 2, 141, 5, 3, 4, 'Rage', 1.1, 'Warrior', 3, 'Berserk');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(12, 0.1, 2.5, 140, 0.1, 10, 36, 0.1, 455, 4.5, 2.3, 4.6, -1, 'Taunt', 'Idle Blinking', 'Hurt', 'Dying', 'Idle', 'Shooting', 'Taunt', 'Walking', 'Kick', 12, 2.5, 140, 5, 3, 4.5, 'Shoot', 36, 'Shooter', 2.3, 'Arbalist');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(12, 0.1, 2, 100, 0.1, 10, 12, 0.1, 0.65, 4, 4, 8, -1, 'Attacking', 'Idle Blinking', 'Hurt', 'Dying', 'Idle', 'Attacking', 'Taunt', 'Walking', 'Kick', 12, 2, 100, 5, 3, 4, 'StunCircle', 12, 'Warrior', 4, 'Barbarian');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(12.5, 0.1, 2.5, 140, 0.1, 10, 12.5, 0.1, 0.75, 4.4, 3, 6, -1, 'Attacking', 'Idle Blink', 'Hurt', 'Dying', 'Idle', 'Attacking', 'Taunt', 'Walking', 'Kick', 12.5, 2.5, 140, 5, 3, 4.4, 'StunCircle', 12.5, 'Warrior', 3, 'Warrior');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(18, 0.1, 2, 90, 0.1, 10, 12.5, 0.1, 70, 4, 4, 8, -1, 'Attacking', 'Idle Blinking', 'Hurt', 'Dying', 'Idle', 'Attacking', 'Taunt', 'Walking', 'Kick', 18, 2, 90, 5, 3, 4, 'Toxic', 12.5, 'Warrior', 4, 'Poisoner');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(20, 0.1, 2, 75, 0.095, 10, 24, 1.5, 100, 4, 3, 6, -1, 'Attacking', 'Idle Blinking', 'Hurt', 'Dying', 'Idle', 'Attacking', 'Taunt', 'Walking', 'Kick', 20, 2, 75, 5, 3, 4, 'Hailstorm', 24, 'Shooter', 3, 'Snowman');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(22, 0.0983, 2, 120, 0.1, 10, 1.1, 2, null, 6, 3, 6, -1, 'Attacking', 'Idle Blinking', 'Hurt', 'Dying', 'Idle', 'Taunt', 'Taunt', 'Walking', 'Kick', 22, 2, 120, 5, 2, 6, 'Invisibility', 1.1, 'Warrior', 3, 'EvilDwarf');
INSERT INTO public."Hero"("DAMAGE0", "DAMAGEA", "DAMAGEDELAY", "MAXHP0", "MAXHPA", "MAXSTEP", "SPEC0", "SPECA", "SPECB", "SPECDELAY", "SPEED0", "SPEEDA", "actualSpeed", "animationAttack", "animationBlinking", "animationDamage", "animationDying", "animationIdle", "animationSpec", "animationTaunt", "animationWalking", "attackType", "attackDamage", "attackDelay", "maxHp", "maxLevel", "rarity", "specDelay", "specType", "specValue", "specialty", "speed", "type") VALUES(10, 0.1, 2, 90, 0.1, 10, 20, 0.1, 1000, 3.1, 3, 6, -1, 'Attacking', 'Idle Blinking', 'Hurt', 'Dying', 'Idle', 'Shooting', 'Taunt', 'Walking', 'Kick', 10, 2, 90, 5, 3, 3.1, 'WildArrow', 20, 'Shooter', 3, 'Rogue');


